Error: Cannot find module 'sass.js'
var sassJs = require('sass'),
need modify ，will fixed it：


 ERROR in ./src/style/index.scss (./node_modules/css-loader/dist/cjs.js??ref--2-2!./node_modules/postcss-loader/src??ref--2-3!./node_modules/sassjs-loader!./node_modules/image-webpack-loader??ref--5!./src/style/index.scss)
    Module build failed (from ./node_modules/sassjs-loader/index.js):
    Error: Cannot find module 'sass.js'
        at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
        at Function.Module._load (internal/modules/cjs/loader.js:562:25)
        at Module.require (internal/modules/cjs/loader.js:690:17)
        at require (internal/modules/cjs/helpers.js:25:18)
        at Object.<anonymous> (C:\www\webpack4-vue2-project-template\node_modules\sassjs-loader\lib\get-path-variations.js:3:14)
        at Module._compile (internal/modules/cjs/loader.js:776:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
        at Module.load (internal/modules/cjs/loader.js:653:32)
        at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
        at Function.Module._load (internal/modules/cjs/loader.js:585:3)
        at Module.require (internal/modules/cjs/loader.js:690:17)
        at require (internal/modules/cjs/helpers.js:25:18)
        at Object.<anonymous> (C:\www\webpack4-vue2-project-template\node_modules\sassjs-loader\index.js:11:25)
        at Module._compile (internal/modules/cjs/loader.js:776:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
        at Module.load (internal/modules/cjs/loader.js:653:32)